apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-namenode
  labels:
    app: hadoop-namenode
spec:
  selector:
    matchLabels:
      app: hadoop-namenode
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hadoop-namenode
    spec:
      containers:
      - image: michaelwangtw/hadoop-namenode:latest
        imagePullPolicy: Always
        name: hadoop-namenode
        env:
          - name: CLUSTER_NAME
            value: "test"
        ports:
          - containerPort: 9870

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-datanode
  labels:
    app: hadoop-datanode
spec:
  selector:
    matchLabels:
      app: hadoop-datanode
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hadoop-datanode
    spec:
      containers:
        - image: michaelwangtw/hadoop-datanode:latest
          imagePullPolicy: Always
          name: hadoop-datanode
          env:
          - name: SERVICE_PRECONDITION
            value: "namenode:9870"